### ISSUE TITLE
Where should I write Android code?

### ISSUE THREAD

**Issue by NBSeven** [bsorrentino/cordova-broadcaster#39]
I'm a front-end engineer and don't know anything about Android....Now I have  a web-project and use cordova to build apk but i dont konw whitch .java file to write your android code ... thanks

**Comment by bsorrentino** [comment]
Hi

I’m not sure to have understood the question

 If you’d want use this plugin  you should have some needs that implies to write some native (java) code, otherwise I don’t understand the reason to use it.

However when you use cordova-cli to generate the android platform and add such plugin,  some java stuff is automatically generated. Take a look in platform/Android folder

**Comment by bsorrentino** [comment]
Hi @NBSeven 

Don't worry about english. Code that you shared seems written in a sort of **NativeScript**.

If I well understood it ... this plugin is the perfect choice, just you have to translate it in pure android/java native code.

if your deadline is not imminent I can help you. Let me know
